version: '3.7'
services:
  web:
    build: .
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - .:/home
    ports:
      - 80:3000
    command: bash -c "bin/setup && bundle exec rails s -b 0.0.0.0"
